spring:
  h2:
    console:
      enabled: true         # 콘솔 활성화
      path: /h2-console     # 접속 경로 설정

  datasource:
    url: jdbc:h2:tcp://localhost/~/ballkeeper
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 애플리케이션 실행 시점에 테이블을 지우고 재생성
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: jS8AqRS+8vwfXQFGrT+HhvYdwCJNdCQOOPXunEsFmGA=
  access-token-validity-in-seconds: 3600